name: flutter_localizacao
description: "Trabalhando com localizacao"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.1
  provider: ^6.1.5+1
  geolocator: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
